"""Add symptom end time

Revision ID: 0c4cde7813c7
Revises: 3fcaa82bc5f8
Create Date: 2026-08-10 07:04:24.031782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c4cde7813c7'
down_revision = '3fcaa82bc5f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('symptom_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_symptom_events_ended_at'), ['ended_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('symptom_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_symptom_events_ended_at'))
        batch_op.drop_column('ended_at')

    # ### end Alembic commands ###
