"""Add food risk component model

Revision ID: 23fb65466777
Revises: 0c4cde7813c7
Create Date: 2026-08-10 07:28:48.960738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23fb65466777'
down_revision = '0c4cde7813c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_components', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_components_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_components_name'), ['name'], unique=True)

    op.create_table('food_risk_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('risk_component_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), server_default='automatic', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint("source IN ('automatic', 'manual')", name='ck_food_risk_source'),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['risk_component_id'], ['risk_components.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('food_id', 'risk_component_id', name='uq_food_risk_component')
    )
    with op.batch_alter_table('food_risk_components', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_food_risk_components_food_id'), ['food_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_food_risk_components_risk_component_id'), ['risk_component_id'], unique=False)

    op.create_table('ingredient_risk_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('risk_component_id', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.String(length=30), server_default='certain', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint("confidence IN ('certain', 'typical', 'product_dependent')", name='ck_ingredient_risk_confidence'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['risk_component_id'], ['risk_components.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ingredient_id', 'risk_component_id', name='uq_ingredient_risk_component')
    )
    with op.batch_alter_table('ingredient_risk_components', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingredient_risk_components_ingredient_id'), ['ingredient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingredient_risk_components_risk_component_id'), ['risk_component_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient_risk_components', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingredient_risk_components_risk_component_id'))
        batch_op.drop_index(batch_op.f('ix_ingredient_risk_components_ingredient_id'))

    op.drop_table('ingredient_risk_components')
    with op.batch_alter_table('food_risk_components', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_food_risk_components_risk_component_id'))
        batch_op.drop_index(batch_op.f('ix_food_risk_components_food_id'))

    op.drop_table('food_risk_components')
    with op.batch_alter_table('risk_components', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_components_name'))
        batch_op.drop_index(batch_op.f('ix_risk_components_category'))

    op.drop_table('risk_components')
    # ### end Alembic commands ###
