"""Add symptom images

Revision ID: 3fcaa82bc5f8
Revises: 9f371ed9cc57
Create Date: 2026-08-09 07:28:51.065988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fcaa82bc5f8'
down_revision = '9f371ed9cc57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('symptom_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symptom_event_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['symptom_event_id'], ['symptom_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('symptom_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_symptom_images_symptom_event_id'), ['symptom_event_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('symptom_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_symptom_images_symptom_event_id'))

    op.drop_table('symptom_images')
    # ### end Alembic commands ###
