"""Add default medication

Revision ID: 5018c67dde97
Revises: 598ad3492bb9
Create Date: 2026-08-10 13:06:59.739867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5018c67dde97'
down_revision = '598ad3492bb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table(
        "medications",
        schema=None,
    ) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_default",
                sa.Boolean(),
                server_default=sa.text("false"),
                nullable=False,
            )
        )

    op.execute(
        """
        UPDATE medications
        SET is_default = true
        WHERE id = (
            SELECT id
            FROM medications
            WHERE active = true
            ORDER BY
                CASE
                    WHEN LOWER(name) = LOWER('Cetirizin')
                    THEN 0
                    ELSE 1
                END,
                id
            LIMIT 1
        )
        """
    )

    with op.batch_alter_table(
        "medications",
        schema=None,
    ) as batch_op:
        batch_op.create_index(
            "uq_medications_one_default",
            ["is_default"],
            unique=True,
            postgresql_where=sa.text(
                "is_default = true"
            ),
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.drop_index('uq_medications_one_default', postgresql_where=sa.text('is_default = true'))
        batch_op.drop_column('is_default')

    # ### end Alembic commands ###
