"""Add enabled flag to food risk components

Revision ID: 598ad3492bb9
Revises: 23fb65466777
Create Date: 2026-08-10 10:09:00.858702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '598ad3492bb9'
down_revision = '23fb65466777'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_risk_components', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_risk_components', schema=None) as batch_op:
        batch_op.drop_column('enabled')

    # ### end Alembic commands ###
