"""Add active flag to events

Revision ID: 9f371ed9cc57
Revises: a97e7c77b313
Create Date: 2026-08-09 06:58:55.339116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f371ed9cc57'
down_revision = 'a97e7c77b313'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table(
        'events',
        schema=None
    ) as batch_op:

        batch_op.add_column(
            sa.Column(
                'active',
                sa.Boolean(),
                server_default=sa.true(),
                nullable=False
            )
        )

        batch_op.create_index(
            batch_op.f('ix_events_active'),
            ['active'],
            unique=False
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_active'))
        batch_op.drop_column('active')

    # ### end Alembic commands ###
