"""Initial SymptomTracker data model

Revision ID: a97e7c77b313
Revises: 
Create Date: 2026-08-09 06:47:53.132399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a97e7c77b313'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('body_parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_occurred_at'), ['occurred_at'], unique=False)

    op.create_table('foods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('brand', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_foods_name'), ['name'], unique=False)

    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingredients_name'), ['name'], unique=True)

    op.create_table('medications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('symptom_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('food_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    with op.batch_alter_table('food_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_food_events_food_id'), ['food_id'], unique=False)

    op.create_table('food_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('image_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('food_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_food_images_food_id'), ['food_id'], unique=False)

    op.create_table('food_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('food_id', 'ingredient_id', name='uq_food_ingredient')
    )
    op.create_table('medication_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('medication_id', sa.Integer(), nullable=False),
    sa.Column('dose', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_table('symptom_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('symptom_type_id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=True),
    sa.CheckConstraint('severity IS NULL OR (severity >= 0 AND severity <= 10)', name='ck_symptom_severity_0_10'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['symptom_type_id'], ['symptom_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    with op.batch_alter_table('symptom_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_symptom_events_symptom_type_id'), ['symptom_type_id'], unique=False)

    op.create_table('symptom_event_body_parts',
    sa.Column('symptom_event_id', sa.Integer(), nullable=False),
    sa.Column('body_part_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['body_part_id'], ['body_parts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['symptom_event_id'], ['symptom_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('symptom_event_id', 'body_part_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('symptom_event_body_parts')
    with op.batch_alter_table('symptom_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_symptom_events_symptom_type_id'))

    op.drop_table('symptom_events')
    op.drop_table('medication_events')
    op.drop_table('food_ingredients')
    with op.batch_alter_table('food_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_food_images_food_id'))

    op.drop_table('food_images')
    with op.batch_alter_table('food_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_food_events_food_id'))

    op.drop_table('food_events')
    op.drop_table('symptom_types')
    op.drop_table('medications')
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingredients_name'))

    op.drop_table('ingredients')
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_foods_name'))

    op.drop_table('foods')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_events_event_type'))

    op.drop_table('events')
    op.drop_table('body_parts')
    # ### end Alembic commands ###
