"""Add multilingual reference translations

Revision ID: c40bb29dbad8
Revises: 5018c67dde97
Create Date: 2026-08-14 07:42:27.164097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c40bb29dbad8'
down_revision = '5018c67dde97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('body_part_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body_part_id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['body_part_id'], ['body_parts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('body_part_id', 'language_code', name='uq_body_part_translation_language')
    )
    with op.batch_alter_table('body_part_translations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_body_part_translations_body_part_id'), ['body_part_id'], unique=False)

    op.create_table('ingredient_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ingredient_id', 'language_code', name='uq_ingredient_translation_language')
    )
    with op.batch_alter_table('ingredient_translations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingredient_translations_ingredient_id'), ['ingredient_id'], unique=False)

    op.create_table('risk_component_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('risk_component_id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['risk_component_id'], ['risk_components.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('risk_component_id', 'language_code', name='uq_risk_component_translation_language')
    )
    with op.batch_alter_table('risk_component_translations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_component_translations_risk_component_id'), ['risk_component_id'], unique=False)

    op.create_table('symptom_type_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symptom_type_id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['symptom_type_id'], ['symptom_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symptom_type_id', 'language_code', name='uq_symptom_type_translation_language')
    )
    with op.batch_alter_table('symptom_type_translations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_symptom_type_translations_symptom_type_id'), ['symptom_type_id'], unique=False)

    # A meglévő törzsadatok a jelenlegi alkalmazásban
    # magyar nyelvűek. Ezeket változtatás nélkül
    # bemásoljuk a fordítástáblákba hu nyelven.
    #
    # A forrásrekordok ID-ja és neve nem változik.

    op.execute(
        """
        INSERT INTO ingredient_translations (
            ingredient_id,
            language_code,
            name
        )
        SELECT
            id,
            'hu',
            name
        FROM ingredients
        ON CONFLICT (
            ingredient_id,
            language_code
        )
        DO NOTHING
        """
    )

    op.execute(
        """
        INSERT INTO risk_component_translations (
            risk_component_id,
            language_code,
            name,
            description
        )
        SELECT
            id,
            'hu',
            name,
            description
        FROM risk_components
        ON CONFLICT (
            risk_component_id,
            language_code
        )
        DO NOTHING
        """
    )

    op.execute(
        """
        INSERT INTO symptom_type_translations (
            symptom_type_id,
            language_code,
            name
        )
        SELECT
            id,
            'hu',
            name
        FROM symptom_types
        ON CONFLICT (
            symptom_type_id,
            language_code
        )
        DO NOTHING
        """
    )

    op.execute(
        """
        INSERT INTO body_part_translations (
            body_part_id,
            language_code,
            name
        )
        SELECT
            id,
            'hu',
            name
        FROM body_parts
        ON CONFLICT (
            body_part_id,
            language_code
        )
        DO NOTHING
        """
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('symptom_type_translations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_symptom_type_translations_symptom_type_id'))

    op.drop_table('symptom_type_translations')
    with op.batch_alter_table('risk_component_translations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_component_translations_risk_component_id'))

    op.drop_table('risk_component_translations')
    with op.batch_alter_table('ingredient_translations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingredient_translations_ingredient_id'))

    op.drop_table('ingredient_translations')
    with op.batch_alter_table('body_part_translations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_body_part_translations_body_part_id'))

    op.drop_table('body_part_translations')
    # ### end Alembic commands ###
